from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine


def run_prototype_migrations(engine: Engine) -> None:
    """Apply minimal additive migrations needed for prototype evolution."""
    inspector = inspect(engine)
    tables = set(inspector.get_table_names())

    if "trend_runs" in tables:
        columns = {col["name"] for col in inspector.get_columns("trend_runs")}
        if "selector_config" not in columns:
            if engine.dialect.name == "postgresql":
                ddl = "ALTER TABLE trend_runs ADD COLUMN selector_config JSONB"
            else:
                ddl = "ALTER TABLE trend_runs ADD COLUMN selector_config JSON"
            with engine.begin() as conn:
                conn.execute(text(ddl))

    if "personas" not in tables:
        payload_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE personas (
                        id {id_type},
                        persona_id VARCHAR(128) NOT NULL UNIQUE,
                        name VARCHAR(256) NOT NULL,
                        payload {payload_type} NOT NULL,
                        source_path TEXT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_personas_persona_id ON personas (persona_id)"))

    if "influencers" not in tables:
        hashtags_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE influencers (
                        id {id_type},
                        influencer_id VARCHAR(128) NOT NULL UNIQUE,
                        name VARCHAR(256) NOT NULL,
                        reference_image_path TEXT NULL,
                        description TEXT NULL,
                        hashtags {hashtags_type} NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_influencers_influencer_id ON influencers (influencer_id)"))
