from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine


def run_prototype_migrations(engine: Engine) -> None:
    """Apply minimal additive migrations needed for prototype evolution."""
    inspector = inspect(engine)
    tables = set(inspector.get_table_names())

    if "trend_runs" in tables:
        columns = {col["name"] for col in inspector.get_columns("trend_runs")}
        if "selector_config" not in columns:
            if engine.dialect.name == "postgresql":
                ddl = "ALTER TABLE trend_runs ADD COLUMN selector_config JSONB"
            else:
                ddl = "ALTER TABLE trend_runs ADD COLUMN selector_config JSON"
            with engine.begin() as conn:
                conn.execute(text(ddl))

    if "personas" not in tables:
        payload_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE personas (
                        id {id_type},
                        persona_id VARCHAR(128) NOT NULL UNIQUE,
                        name VARCHAR(256) NOT NULL,
                        payload {payload_type} NOT NULL,
                        source_path TEXT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_personas_persona_id ON personas (persona_id)"))

    if "influencers" not in tables:
        hashtags_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE influencers (
                        id {id_type},
                        influencer_id VARCHAR(128) NOT NULL UNIQUE,
                        name VARCHAR(256) NOT NULL,
                        reference_image_path TEXT NULL,
                        description TEXT NULL,
                        hashtags {hashtags_type} NULL,
                        video_suggestions_requirement TEXT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_influencers_influencer_id ON influencers (influencer_id)"))
    elif "influencers" in tables:
        columns = {col["name"] for col in inspector.get_columns("influencers")}
        if "video_suggestions_requirement" not in columns:
            with engine.begin() as conn:
                conn.execute(text("ALTER TABLE influencers ADD COLUMN video_suggestions_requirement TEXT"))

    if "picture_ideas" not in tables:
        json_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE picture_ideas (
                        id {id_type},
                        influencer_id VARCHAR(128) NOT NULL,
                        platforms {json_type} NOT NULL,
                        source_run_ids {json_type} NULL,
                        title VARCHAR(256) NOT NULL,
                        prompt TEXT NOT NULL,
                        hashtags {json_type} NULL,
                        score FLOAT NOT NULL DEFAULT 0,
                        rationale TEXT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_picture_ideas_influencer_id ON picture_ideas (influencer_id)"))

    if "generated_images" not in tables:
        json_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE generated_images (
                        id {id_type},
                        influencer_id VARCHAR(128) NOT NULL,
                        picture_idea_id INTEGER NULL,
                        model VARCHAR(128) NOT NULL,
                        prompt TEXT NOT NULL,
                        hashtags {json_type} NULL,
                        reference_image_path TEXT NULL,
                        output_image_path TEXT NOT NULL,
                        mime_type VARCHAR(64) NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_generated_images_influencer_id ON generated_images (influencer_id)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_generated_images_picture_idea_id ON generated_images (picture_idea_id)"))
    elif "generated_images" in tables:
        columns = {col["name"] for col in inspector.get_columns("generated_images")}
        if "hashtags" not in columns:
            ddl = "ALTER TABLE generated_images ADD COLUMN hashtags JSONB" if engine.dialect.name == "postgresql" else "ALTER TABLE generated_images ADD COLUMN hashtags JSON"
            with engine.begin() as conn:
                conn.execute(text(ddl))

    json_type = "JSONB" if engine.dialect.name == "postgresql" else "JSON"
    id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if engine.dialect.name == "postgresql" else "INTEGER PRIMARY KEY"

    if "x_trend_runs" not in tables:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE x_trend_runs (
                        id {id_type},
                        status VARCHAR(32) NOT NULL,
                        query TEXT NULL,
                        location_woeid INTEGER NULL,
                        started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        completed_at TIMESTAMP NULL,
                        summary {json_type} NULL,
                        error_message TEXT NULL
                    )
                    """
                )
            )

    if "x_trend_topics" not in tables:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE x_trend_topics (
                        id {id_type},
                        run_id INTEGER NOT NULL,
                        name VARCHAR(512) NOT NULL,
                        trend_url TEXT NULL,
                        tweet_volume INTEGER NULL,
                        position INTEGER NULL,
                        raw_payload {json_type} NULL
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_trend_topics_run_id ON x_trend_topics (run_id)"))

    if "x_posts" not in tables:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE x_posts (
                        id {id_type},
                        run_id INTEGER NOT NULL,
                        post_id VARCHAR(64) NOT NULL,
                        query TEXT NULL,
                        author_id VARCHAR(64) NULL,
                        author_username VARCHAR(256) NULL,
                        author_name VARCHAR(256) NULL,
                        text TEXT NOT NULL,
                        lang VARCHAR(32) NULL,
                        conversation_id VARCHAR(64) NULL,
                        created_at_x TIMESTAMP NULL,
                        like_count INTEGER NOT NULL DEFAULT 0,
                        repost_count INTEGER NOT NULL DEFAULT 0,
                        reply_count INTEGER NOT NULL DEFAULT 0,
                        quote_count INTEGER NOT NULL DEFAULT 0,
                        bookmark_count INTEGER NOT NULL DEFAULT 0,
                        impression_count INTEGER NOT NULL DEFAULT 0,
                        media_view_count INTEGER NOT NULL DEFAULT 0,
                        has_images BOOLEAN NOT NULL DEFAULT 0,
                        popularity_score FLOAT NOT NULL DEFAULT 0,
                        permalink TEXT NULL,
                        raw_payload {json_type} NULL
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_posts_run_id ON x_posts (run_id)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_posts_post_id ON x_posts (post_id)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_posts_author_id ON x_posts (author_id)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_posts_has_images ON x_posts (has_images)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_posts_popularity_score ON x_posts (popularity_score)"))
    elif "x_posts" in tables:
        columns = {col["name"] for col in inspector.get_columns("x_posts")}
        if "media_view_count" not in columns:
            with engine.begin() as conn:
                conn.execute(text("ALTER TABLE x_posts ADD COLUMN media_view_count INTEGER NOT NULL DEFAULT 0"))

    if "x_post_media" not in tables:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE x_post_media (
                        id {id_type},
                        post_row_id INTEGER NOT NULL,
                        media_key VARCHAR(128) NULL,
                        media_type VARCHAR(64) NULL,
                        media_url TEXT NULL,
                        preview_image_url TEXT NULL,
                        width INTEGER NULL,
                        height INTEGER NULL,
                        alt_text TEXT NULL,
                        raw_payload {json_type} NULL
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_post_media_post_row_id ON x_post_media (post_row_id)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_post_media_media_key ON x_post_media (media_key)"))

    if "x_drafts" not in tables:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE x_drafts (
                        id {id_type},
                        run_id INTEGER NOT NULL,
                        topic VARCHAR(512) NULL,
                        source_post_ids {json_type} NULL,
                        title VARCHAR(256) NOT NULL,
                        draft_text TEXT NOT NULL,
                        image_brief TEXT NULL,
                        hook_pattern VARCHAR(256) NULL,
                        rationale TEXT NULL,
                        score FLOAT NOT NULL DEFAULT 0,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            conn.execute(text("CREATE INDEX IF NOT EXISTS ix_x_drafts_run_id ON x_drafts (run_id)"))
